version: '3.4'

services:
  web:
    image: vdonthireddy/vjapp:1.0
    environment:
      CLIENT_PORT: 8081
      SERVICE_HOST: http://api
      SERVICE_PORT: 8080
    ports:
     - "8081:8081"
    depends_on:
     - api
  api:
    image: vdonthireddy/vjservice:1.0
    ports:
     - "8080:8080"
