version: '3'

services:
  web:
    image: vdonthireddy/vjapp:1.0
    environment:
      CLIENT_PORT: 9435
      SERVICE_HOST: http://api
      SERVICE_PORT: 9436
    ports:
     - "9435:9435"
    depends_on:
     - api
  api:
    image: vdonthireddy/vjnodeservice:1.0
    ports:
     - "9436:9436"
